[package]
name = "fftw-bin"
version = "0.1.0"
authors = ["Alexandre Péré <aPere3@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fftw = {path = "../fftw"}
f128 = "0.2.9"
